const fs = require('fs');

let content = `import { User, Resource, Order, Message, Rating, Activity, Report, School } from '../types';

export const SCHOOLS: School[] = [
  { id: 'sch_1', name: 'University of Lagos', shortName: 'UNILAG', domain: 'unilag.edu.ng', status: 'ACTIVE' },
  { id: 'sch_2', name: 'Obafemi Awolowo University', shortName: 'OAU', domain: 'oauife.edu.ng', status: 'ACTIVE' },
  { id: 'sch_3', name: 'Covenant University', shortName: 'CU', domain: 'covenantuniversity.edu.ng', status: 'ACTIVE' },
  { id: 'sch_4', name: 'University of Ibadan', shortName: 'UI', domain: 'ui.edu.ng', status: 'ACTIVE' },
];

export const users: Record<string, User> = {
  currentUser: {
    id: 'u_1',
    name: 'Alex Johnson',
    initials: 'AJ',
    isVerified: true,
    verificationStatus: 'VERIFIED',
    accountStatus: 'ACTIVE',
    role: 'STUDENT',
    schoolId: 'sch_1',
    rating: 4.8,
    totalRatings: 12,
    completedOrders: 5,
    completionRate: 100,
  },
  ada: {
    id: 'u_2',
    name: 'Ada Obi',
    initials: 'AO',
    isVerified: true,
    verificationStatus: 'VERIFIED',
    accountStatus: 'ACTIVE',
    role: 'STUDENT',
    schoolId: 'sch_1',
    rating: 4.9,
    totalRatings: 24,
    completedOrders: 15,
  },
  chinedu: {
    id: 'u_3',
    name: 'Chinedu Eze',
    initials: 'CE',
    isVerified: true,
    verificationStatus: 'VERIFIED',
    accountStatus: 'ACTIVE',
    role: 'STUDENT',
    schoolId: 'sch_1',
    rating: 4.5,
    totalRatings: 8,
    completedOrders: 3,
  },
  bolaji: {
    id: 'u_4',
    name: 'Bolaji Alabi',
    initials: 'BA',
    isVerified: false,
    verificationStatus: 'UNVERIFIED',
    accountStatus: 'ACTIVE',
    role: 'STUDENT',
    schoolId: 'sch_1',
  },
  tobi: {
    id: 'u_5',
    name: 'Tobi Bakare',
    initials: 'TB',
    isVerified: true,
    verificationStatus: 'VERIFIED',
    accountStatus: 'ACTIVE',
    role: 'STUDENT',
    schoolId: 'sch_1',
    rating: 4.2,
    totalRatings: 5,
    completedOrders: 2,
  },
  zainab: {
    id: 'u_6',
    name: 'Zainab Bello',
    initials: 'ZB',
    isVerified: true,
    verificationStatus: 'VERIFIED',
    accountStatus: 'ACTIVE',
    role: 'STUDENT',
    schoolId: 'sch_1',
    rating: 5.0,
    totalRatings: 3,
    completedOrders: 3,
  },
  ngozi: {
    id: 'u_7',
    name: 'Ngozi Okafor',
    initials: 'NO',
    isVerified: true,
    verificationStatus: 'VERIFIED',
    accountStatus: 'ACTIVE',
    role: 'STUDENT',
    schoolId: 'sch_1',
    rating: 4.7,
    totalRatings: 10,
    completedOrders: 6,
  },
  adminUser: {
    id: 'a_1',
    name: 'Boski Admin',
    initials: 'AD',
    isVerified: true,
    verificationStatus: 'VERIFIED',
    accountStatus: 'ACTIVE',
    role: 'ADMIN',
    schoolId: 'sch_1',
  },
};

export const currentUser = users.currentUser;

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'r_8',
    type: 'SKILL',
    intent: 'HAVE',
    title: 'Figma UI/UX Design Help',
    description: 'I can help you design clean, modern mobile app prototypes using Figma. Good for final year projects.',
    provider: currentUser,
    status: 'available',
    createdAt: '2023-10-27T08:00:00Z',
    location: 'Tech Hub',
    price: 5000,
    currency: 'NGN',
    pricingUnit: 'session',
  },
  {
    id: 'r_1',
    type: 'ITEM',
    intent: 'HAVE',
    title: 'Casio fx-991EX Scientific Calculator',
    description: 'Barely used, perfect for engineering exams.',
    provider: users.ada,
    status: 'available',
    createdAt: '2023-10-25T10:00:00Z',
    location: 'Engineering Block',
    price: 1500,
    currency: 'NGN',
    pricingUnit: 'day',
  },
  {
    id: 'r_2',
    type: 'SKILL',
    intent: 'HAVE',
    title: 'Photography & Headshots',
    description: 'I can take professional LinkedIn headshots. I use a Canon EOS R with a 50mm lens.',
    provider: users.chinedu,
    status: 'available',
    createdAt: '2023-10-24T14:30:00Z',
    location: 'Student Union Building',
    price: 10000,
    currency: 'NGN',
    pricingUnit: 'project',
  },
  {
    id: 'r_3',
    type: 'ITEM',
    intent: 'NEED',
    title: 'Need a tripod for a weekend project',
    description: 'Shooting a short film for my media assignment this weekend. Will return by Monday. Needs to be sturdy enough to hold a DSLR.',
    provider: users.bolaji,
    status: 'available',
    createdAt: '2023-10-25T08:15:00Z',
    location: 'Faculty of Arts',
    budget: 3000,
  },
  {
    id: 'r_4',
    type: 'ITEM',
    intent: 'HAVE',
    title: 'HDMI to USB-C Adapter',
    description: 'Works with Mac and most Windows laptops.',
    provider: users.tobi,
    status: 'available',
    createdAt: '2023-10-23T16:45:00Z',
    location: 'Library, 2nd Floor',
    price: 1000,
    currency: 'NGN',
    pricingUnit: 'day',
  },
  {
    id: 'r_5',
    type: 'SKILL',
    intent: 'HAVE',
    title: 'MTH101 / MTH102 Tutoring',
    description: 'I can help you prepare for the upcoming CA.',
    provider: users.zainab,
    status: 'available',
    createdAt: '2023-10-22T09:20:00Z',
    location: 'Library Study Rooms',
    price: 3000,
    currency: 'NGN',
    pricingUnit: 'session',
  },
  {
    id: 'r_6',
    type: 'ITEM',
    intent: 'HAVE',
    title: 'Basketball',
    description: 'Standard size basketball. Good for pickup games.',
    provider: users.ngozi,
    status: 'available',
    createdAt: '2023-10-25T12:00:00Z',
    location: 'Sports Center',
    price: 1000,
    currency: 'NGN',
    pricingUnit: 'day',
  },
  {
    id: 'r_7',
    type: 'HELP',
    intent: 'NEED',
    title: 'Who can help with Video Editing?',
    description: 'I have some raw clips from our faculty week that need to be stitched together for a 1-min reel.',
    provider: users.ada,
    status: 'available',
    createdAt: '2023-10-26T07:10:00Z',
    budget: 5000,
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg_1',
    orderId: 'ex_1',
    senderId: currentUser.id,
    body: 'Hi Ada, is the calculator still available for this week?',
    createdAt: new Date(Date.now() - 86000000).toISOString(),
    readAt: new Date(Date.now() - 85000000).toISOString(),
  },
  {
    id: 'msg_2',
    orderId: 'ex_1',
    senderId: users.ada.id,
    body: 'Yes it is! When do you need to pick it up?',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    // Unread
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ex_1',
    resourceId: 'r_1',
    customerId: currentUser.id,
    providerId: users.ada.id,
    resourceType: 'ITEM',
    status: 'REQUESTED',
    paymentStatus: 'UNPAID',
    price: 3000,
    currency: 'NGN',
    pricingUnit: 'day',
    requestedAt: new Date(Date.now() - 86400000).toISOString(),
    startDate: '2023-11-01',
    endDate: '2023-11-03',
    message: 'Need it for my MTH101 test.',
  },
  {
    id: 'ex_2',
    resourceId: 'r_2',
    customerId: currentUser.id,
    providerId: users.chinedu.id,
    resourceType: 'SKILL',
    status: 'ACCEPTED',
    paymentStatus: 'PAID',
    price: 10000,
    currency: 'NGN',
    pricingUnit: 'project',
    requestedAt: new Date(Date.now() - 172800000).toISOString(),
    timing: 'This Friday',
    message: 'I need some headshots for LinkedIn.',
  },
  {
    id: 'ex_4',
    resourceId: 'r_4',
    customerId: users.ada.id,
    providerId: users.tobi.id,
    resourceType: 'ITEM',
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    price: 2000,
    currency: 'NGN',
    pricingUnit: 'day',
    requestedAt: new Date(Date.now() - 604800000).toISOString(),
    startDate: '2023-10-24',
    endDate: '2023-10-25',
    message: 'Can I rent this for my presentation?',
  },
];

export const INITIAL_RATINGS: Rating[] = [
  {
    id: 'rat_1',
    orderId: 'ex_4',
    fromUserId: users.ada.id,
    toUserId: users.tobi.id,
    score: 5,
    feedback: 'Tobi was very helpful and the adapter worked perfectly!',
    createdAt: new Date(Date.now() - 500000000).toISOString(),
  }
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act_1',
    type: 'ORDER_REQUEST_RECEIVED',
    userId: 'u_1',
    actorId: 'u_2',
    orderId: 'ex_2', 
    resourceId: 'r_8',
    title: 'Ada requested your skill',
    description: 'Ada wants to book your Figma UI/UX Design Help.',
    createdAt: '2023-10-31T09:00:00Z',
    readAt: '2023-10-31T09:05:00Z'
  },
  {
    id: 'act_2',
    type: 'ORDER_REQUEST_ACCEPTED',
    userId: 'u_1',
    actorId: 'u_3',
    orderId: 'ex_1', 
    resourceId: 'r_2',
    title: 'Your order was accepted',
    description: 'Chinedu accepted your order for Photography & Headshots.',
    createdAt: '2023-10-30T14:30:00Z',
    readAt: '2023-10-30T15:00:00Z'
  },
  {
    id: 'act_3',
    type: 'NEW_ORDER_MESSAGE',
    userId: 'u_1',
    actorId: 'u_3',
    orderId: 'ex_1',
    messageId: 'm_1',
    title: 'New message from Chinedu',
    description: 'When can we meet up?',
    createdAt: '2023-10-30T15:05:00Z',
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep_1',
    reporterId: 'u_1',
    targetType: 'USER',
    targetId: 'u_4',
    reason: 'NO_SHOW',
    description: 'He never showed up to drop off the item.',
    status: 'OPEN',
    createdAt: '2023-11-01T10:00:00Z',
  }
];
`;

fs.writeFileSync('src/data/mockData.ts', content);
console.log('Fixed mockData.ts');
